# Numpy

In [120]:
import numpy as np
from pyarrow import table

firstArray = np.array([1, 2, 3.2])
secondArray = np.array([4, -2, 6])
print(firstArray, "*************", type(firstArray), firstArray.dtype)
print(secondArray, "*************", type(secondArray), secondArray.dtype)
TwoDimArray = firstArray + secondArray
print(TwoDimArray, "*************", type(TwoDimArray))

TwoDimArray = firstArray - secondArray
print(TwoDimArray, "*************", type(TwoDimArray))

TwoDimArray = firstArray * secondArray
print(TwoDimArray, "*************", type(TwoDimArray))

[1.  2.  3.2] ************* <class 'numpy.ndarray'> float64
[ 4 -2  6] ************* <class 'numpy.ndarray'> int64
[5.  0.  9.2] ************* <class 'numpy.ndarray'>
[-3.   4.  -2.8] ************* <class 'numpy.ndarray'>
[ 4.  -4.  19.2] ************* <class 'numpy.ndarray'>


In [122]:
firstArray = np.array([1, 2, 3], dtype=np.int64)
secondArray = np.array([1, 2, 3.0], dtype=np.float64)
thirdArray = np.array([1, 2, 3.0], dtype="f")
print(firstArray, "*************", type(firstArray), firstArray.dtype)
print(secondArray, "*************", type(secondArray), secondArray.dtype)
print(thirdArray, "*************", type(thirdArray), thirdArray.dtype)
print(thirdArray[::-1])

[1 2 3] ************* <class 'numpy.ndarray'> int64
[1. 2. 3.] ************* <class 'numpy.ndarray'> float64
[1. 2. 3.] ************* <class 'numpy.ndarray'> float32
[3. 2. 1.]


In [132]:
firstArray = np.array([1, 2, 3])
print(firstArray.ndim)

myTwoDimArray = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])
print(myTwoDimArray.ndim)

threeDimArray = np.array([[[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]],
                          [[10, 11, 12],
                           [13, 14, 15],
                           [16, 17, 18]]])

print("*****", threeDimArray.ndim)
print("*****      ", threeDimArray[1, 2, 1])

fourDimArray = np.array([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                          [[10, 11, 12], [13, 14, 15], [16, 17, 18]]],
                         [[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                          [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]])

print("***** fourDimArray", fourDimArray.ndim)
print("***** fourDimArray", fourDimArray.shape)

print(np.array([1]).ndim)
print(np.array(1).ndim)
print(fourDimArray.nbytes, fourDimArray.size, fourDimArray.dtype, fourDimArray.ndim,
      fourDimArray.shape)
print(threeDimArray.nbytes, threeDimArray.size, threeDimArray.dtype, threeDimArray.ndim,
      threeDimArray.shape)

1
2
***** 3
*****       17
***** fourDimArray 4
***** fourDimArray (2, 2, 3, 3)
1
0
288 36 int64 4 (2, 2, 3, 3)
144 18 int64 3 (2, 3, 3)


In [70]:
A = np.arange(10)
print(A)

A = np.arange(100, 1, -2)
print(A)

[0 1 2 3 4 5 6 7 8 9]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]


In [88]:
A = np.random.permutation(np.arange(100, 1, -2))
print(A)

print(np.random.randint(100, 200))

[  6  36  92  90   4  24 100  40  44  16  72  64  30  10  82  76  96  78
  88  66  14  94  86   8  46  98  42  56  68  20  74  52  54  80  22  50
  38  34  58  28  48  60  62  70  84   2  32  12  18  26]
182


In [133]:
fourDimArray = np.array([
  [[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
   [[10, 11, 12], [13, 14, 15], [16, 17, 18]]],
  [[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
   [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]
])

print("*****", fourDimArray.ndim)
print("*****", fourDimArray.shape)

firstArray = np.array([1])
print("*****", firstArray.ndim)

zeroDImArray = np.array(25)
print("*****", zeroDImArray.ndim)
print("*****", zeroDImArray.shape)



***** 4
***** (2, 2, 3, 3)
***** 1
***** 0
***** ()


array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]])

In [109]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
