# Numpy

In [141]:
import numpy as np

A = np.array([1, 2, 3])

In [142]:
print(A)
B = np.arange(2).reshape(2, 1)
print(B)
print(A + B)

[1 2 3]
[[0]
 [1]]
[[1 2 3]
 [2 3 4]]


In [153]:
# hstack

A = np.array([1, 2, 3]).reshape(3, 1)
B = np.array([4, 5, 6, 7, 8, 9]).reshape(3, 2)
print(np.hstack((A, B)))
print(np.hstack((A, B)).shape)


[[1 4 5]
 [2 6 7]
 [3 8 9]]
(3, 3)


In [156]:
# vstack
A = np.array([1, 2, 3]).reshape(1, 3)
B = np.array([4, 5, 6, 7, 8, 9]).reshape(2, 3)
print(np.vstack((A, B)))
print(np.vstack((A, B)).shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [164]:
# sort

A = np.arange(6).reshape(2, 3)
print(A)
print(np.sort(A)[::-1])


[[0 1 2]
 [3 4 5]]
[[3 4 5]
 [0 1 2]]


In [169]:
# Universal functions are very fast
A = np.random.rand(1000000)
%timeit sum(A)
%timeit np.sum(A)


40.7 ms ± 622 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
177 μs ± 405 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
